/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard.index'
import { Route as AuthenticatedDashboardAgentsRouteImport } from './routes/_authenticated/dashboard.agents'
import { Route as AuthenticatedDashboardAiQualityRouteImport } from './routes/_authenticated/dashboard.ai-quality'
import { Route as AuthenticatedDashboardAlertingRouteImport } from './routes/_authenticated/dashboard.alerting'
import { Route as AuthenticatedDashboardAnalyticsRouteImport } from './routes/_authenticated/dashboard.analytics'
import { Route as AuthenticatedDashboardBatchCallRouteImport } from './routes/_authenticated/dashboard.batch-call'
import { Route as AuthenticatedDashboardBillingRouteImport } from './routes/_authenticated/dashboard.billing'
import { Route as AuthenticatedDashboardCallHistoryRouteImport } from './routes/_authenticated/dashboard.call-history'
import { Route as AuthenticatedDashboardChatHistoryRouteImport } from './routes/_authenticated/dashboard.chat-history'
import { Route as AuthenticatedDashboardContactsRouteImport } from './routes/_authenticated/dashboard.contacts'
import { Route as AuthenticatedDashboardIntegrationsRouteImport } from './routes/_authenticated/dashboard.integrations'
import { Route as AuthenticatedDashboardKnowledgeRouteImport } from './routes/_authenticated/dashboard.knowledge'
import { Route as AuthenticatedDashboardLiveMonitoringRouteImport } from './routes/_authenticated/dashboard.live-monitoring'
import { Route as AuthenticatedDashboardPhoneNumbersRouteImport } from './routes/_authenticated/dashboard.phone-numbers'
import { Route as AuthenticatedDashboardSettingsRouteImport } from './routes/_authenticated/dashboard.settings'
import { Route as ApiPublicTelephonyExotelRouteImport } from './routes/api/public/telephony/exotel'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardAgentsRoute =
  AuthenticatedDashboardAgentsRouteImport.update({
    id: '/agents',
    path: '/agents',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardAiQualityRoute =
  AuthenticatedDashboardAiQualityRouteImport.update({
    id: '/ai-quality',
    path: '/ai-quality',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardAlertingRoute =
  AuthenticatedDashboardAlertingRouteImport.update({
    id: '/alerting',
    path: '/alerting',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardAnalyticsRoute =
  AuthenticatedDashboardAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardBatchCallRoute =
  AuthenticatedDashboardBatchCallRouteImport.update({
    id: '/batch-call',
    path: '/batch-call',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardBillingRoute =
  AuthenticatedDashboardBillingRouteImport.update({
    id: '/billing',
    path: '/billing',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardCallHistoryRoute =
  AuthenticatedDashboardCallHistoryRouteImport.update({
    id: '/call-history',
    path: '/call-history',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardChatHistoryRoute =
  AuthenticatedDashboardChatHistoryRouteImport.update({
    id: '/chat-history',
    path: '/chat-history',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardContactsRoute =
  AuthenticatedDashboardContactsRouteImport.update({
    id: '/contacts',
    path: '/contacts',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardIntegrationsRoute =
  AuthenticatedDashboardIntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardKnowledgeRoute =
  AuthenticatedDashboardKnowledgeRouteImport.update({
    id: '/knowledge',
    path: '/knowledge',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardLiveMonitoringRoute =
  AuthenticatedDashboardLiveMonitoringRouteImport.update({
    id: '/live-monitoring',
    path: '/live-monitoring',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardPhoneNumbersRoute =
  AuthenticatedDashboardPhoneNumbersRouteImport.update({
    id: '/phone-numbers',
    path: '/phone-numbers',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardSettingsRoute =
  AuthenticatedDashboardSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const ApiPublicTelephonyExotelRoute =
  ApiPublicTelephonyExotelRouteImport.update({
    id: '/api/public/telephony/exotel',
    path: '/api/public/telephony/exotel',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/dashboard/agents': typeof AuthenticatedDashboardAgentsRoute
  '/dashboard/ai-quality': typeof AuthenticatedDashboardAiQualityRoute
  '/dashboard/alerting': typeof AuthenticatedDashboardAlertingRoute
  '/dashboard/analytics': typeof AuthenticatedDashboardAnalyticsRoute
  '/dashboard/batch-call': typeof AuthenticatedDashboardBatchCallRoute
  '/dashboard/billing': typeof AuthenticatedDashboardBillingRoute
  '/dashboard/call-history': typeof AuthenticatedDashboardCallHistoryRoute
  '/dashboard/chat-history': typeof AuthenticatedDashboardChatHistoryRoute
  '/dashboard/contacts': typeof AuthenticatedDashboardContactsRoute
  '/dashboard/integrations': typeof AuthenticatedDashboardIntegrationsRoute
  '/dashboard/knowledge': typeof AuthenticatedDashboardKnowledgeRoute
  '/dashboard/live-monitoring': typeof AuthenticatedDashboardLiveMonitoringRoute
  '/dashboard/phone-numbers': typeof AuthenticatedDashboardPhoneNumbersRoute
  '/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/api/public/telephony/exotel': typeof ApiPublicTelephonyExotelRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard/agents': typeof AuthenticatedDashboardAgentsRoute
  '/dashboard/ai-quality': typeof AuthenticatedDashboardAiQualityRoute
  '/dashboard/alerting': typeof AuthenticatedDashboardAlertingRoute
  '/dashboard/analytics': typeof AuthenticatedDashboardAnalyticsRoute
  '/dashboard/batch-call': typeof AuthenticatedDashboardBatchCallRoute
  '/dashboard/billing': typeof AuthenticatedDashboardBillingRoute
  '/dashboard/call-history': typeof AuthenticatedDashboardCallHistoryRoute
  '/dashboard/chat-history': typeof AuthenticatedDashboardChatHistoryRoute
  '/dashboard/contacts': typeof AuthenticatedDashboardContactsRoute
  '/dashboard/integrations': typeof AuthenticatedDashboardIntegrationsRoute
  '/dashboard/knowledge': typeof AuthenticatedDashboardKnowledgeRoute
  '/dashboard/live-monitoring': typeof AuthenticatedDashboardLiveMonitoringRoute
  '/dashboard/phone-numbers': typeof AuthenticatedDashboardPhoneNumbersRoute
  '/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/api/public/telephony/exotel': typeof ApiPublicTelephonyExotelRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/_authenticated/dashboard/agents': typeof AuthenticatedDashboardAgentsRoute
  '/_authenticated/dashboard/ai-quality': typeof AuthenticatedDashboardAiQualityRoute
  '/_authenticated/dashboard/alerting': typeof AuthenticatedDashboardAlertingRoute
  '/_authenticated/dashboard/analytics': typeof AuthenticatedDashboardAnalyticsRoute
  '/_authenticated/dashboard/batch-call': typeof AuthenticatedDashboardBatchCallRoute
  '/_authenticated/dashboard/billing': typeof AuthenticatedDashboardBillingRoute
  '/_authenticated/dashboard/call-history': typeof AuthenticatedDashboardCallHistoryRoute
  '/_authenticated/dashboard/chat-history': typeof AuthenticatedDashboardChatHistoryRoute
  '/_authenticated/dashboard/contacts': typeof AuthenticatedDashboardContactsRoute
  '/_authenticated/dashboard/integrations': typeof AuthenticatedDashboardIntegrationsRoute
  '/_authenticated/dashboard/knowledge': typeof AuthenticatedDashboardKnowledgeRoute
  '/_authenticated/dashboard/live-monitoring': typeof AuthenticatedDashboardLiveMonitoringRoute
  '/_authenticated/dashboard/phone-numbers': typeof AuthenticatedDashboardPhoneNumbersRoute
  '/_authenticated/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/api/public/telephony/exotel': typeof ApiPublicTelephonyExotelRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/dashboard/agents'
    | '/dashboard/ai-quality'
    | '/dashboard/alerting'
    | '/dashboard/analytics'
    | '/dashboard/batch-call'
    | '/dashboard/billing'
    | '/dashboard/call-history'
    | '/dashboard/chat-history'
    | '/dashboard/contacts'
    | '/dashboard/integrations'
    | '/dashboard/knowledge'
    | '/dashboard/live-monitoring'
    | '/dashboard/phone-numbers'
    | '/dashboard/settings'
    | '/dashboard/'
    | '/api/public/telephony/exotel'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard/agents'
    | '/dashboard/ai-quality'
    | '/dashboard/alerting'
    | '/dashboard/analytics'
    | '/dashboard/batch-call'
    | '/dashboard/billing'
    | '/dashboard/call-history'
    | '/dashboard/chat-history'
    | '/dashboard/contacts'
    | '/dashboard/integrations'
    | '/dashboard/knowledge'
    | '/dashboard/live-monitoring'
    | '/dashboard/phone-numbers'
    | '/dashboard/settings'
    | '/dashboard'
    | '/api/public/telephony/exotel'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/dashboard'
    | '/_authenticated/dashboard/agents'
    | '/_authenticated/dashboard/ai-quality'
    | '/_authenticated/dashboard/alerting'
    | '/_authenticated/dashboard/analytics'
    | '/_authenticated/dashboard/batch-call'
    | '/_authenticated/dashboard/billing'
    | '/_authenticated/dashboard/call-history'
    | '/_authenticated/dashboard/chat-history'
    | '/_authenticated/dashboard/contacts'
    | '/_authenticated/dashboard/integrations'
    | '/_authenticated/dashboard/knowledge'
    | '/_authenticated/dashboard/live-monitoring'
    | '/_authenticated/dashboard/phone-numbers'
    | '/_authenticated/dashboard/settings'
    | '/_authenticated/dashboard/'
    | '/api/public/telephony/exotel'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicTelephonyExotelRoute: typeof ApiPublicTelephonyExotelRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/agents': {
      id: '/_authenticated/dashboard/agents'
      path: '/agents'
      fullPath: '/dashboard/agents'
      preLoaderRoute: typeof AuthenticatedDashboardAgentsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/ai-quality': {
      id: '/_authenticated/dashboard/ai-quality'
      path: '/ai-quality'
      fullPath: '/dashboard/ai-quality'
      preLoaderRoute: typeof AuthenticatedDashboardAiQualityRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/alerting': {
      id: '/_authenticated/dashboard/alerting'
      path: '/alerting'
      fullPath: '/dashboard/alerting'
      preLoaderRoute: typeof AuthenticatedDashboardAlertingRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/analytics': {
      id: '/_authenticated/dashboard/analytics'
      path: '/analytics'
      fullPath: '/dashboard/analytics'
      preLoaderRoute: typeof AuthenticatedDashboardAnalyticsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/batch-call': {
      id: '/_authenticated/dashboard/batch-call'
      path: '/batch-call'
      fullPath: '/dashboard/batch-call'
      preLoaderRoute: typeof AuthenticatedDashboardBatchCallRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/billing': {
      id: '/_authenticated/dashboard/billing'
      path: '/billing'
      fullPath: '/dashboard/billing'
      preLoaderRoute: typeof AuthenticatedDashboardBillingRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/call-history': {
      id: '/_authenticated/dashboard/call-history'
      path: '/call-history'
      fullPath: '/dashboard/call-history'
      preLoaderRoute: typeof AuthenticatedDashboardCallHistoryRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/chat-history': {
      id: '/_authenticated/dashboard/chat-history'
      path: '/chat-history'
      fullPath: '/dashboard/chat-history'
      preLoaderRoute: typeof AuthenticatedDashboardChatHistoryRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/contacts': {
      id: '/_authenticated/dashboard/contacts'
      path: '/contacts'
      fullPath: '/dashboard/contacts'
      preLoaderRoute: typeof AuthenticatedDashboardContactsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/integrations': {
      id: '/_authenticated/dashboard/integrations'
      path: '/integrations'
      fullPath: '/dashboard/integrations'
      preLoaderRoute: typeof AuthenticatedDashboardIntegrationsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/knowledge': {
      id: '/_authenticated/dashboard/knowledge'
      path: '/knowledge'
      fullPath: '/dashboard/knowledge'
      preLoaderRoute: typeof AuthenticatedDashboardKnowledgeRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/live-monitoring': {
      id: '/_authenticated/dashboard/live-monitoring'
      path: '/live-monitoring'
      fullPath: '/dashboard/live-monitoring'
      preLoaderRoute: typeof AuthenticatedDashboardLiveMonitoringRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/phone-numbers': {
      id: '/_authenticated/dashboard/phone-numbers'
      path: '/phone-numbers'
      fullPath: '/dashboard/phone-numbers'
      preLoaderRoute: typeof AuthenticatedDashboardPhoneNumbersRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/settings': {
      id: '/_authenticated/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof AuthenticatedDashboardSettingsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/api/public/telephony/exotel': {
      id: '/api/public/telephony/exotel'
      path: '/api/public/telephony/exotel'
      fullPath: '/api/public/telephony/exotel'
      preLoaderRoute: typeof ApiPublicTelephonyExotelRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedDashboardRouteChildren {
  AuthenticatedDashboardAgentsRoute: typeof AuthenticatedDashboardAgentsRoute
  AuthenticatedDashboardAiQualityRoute: typeof AuthenticatedDashboardAiQualityRoute
  AuthenticatedDashboardAlertingRoute: typeof AuthenticatedDashboardAlertingRoute
  AuthenticatedDashboardAnalyticsRoute: typeof AuthenticatedDashboardAnalyticsRoute
  AuthenticatedDashboardBatchCallRoute: typeof AuthenticatedDashboardBatchCallRoute
  AuthenticatedDashboardBillingRoute: typeof AuthenticatedDashboardBillingRoute
  AuthenticatedDashboardCallHistoryRoute: typeof AuthenticatedDashboardCallHistoryRoute
  AuthenticatedDashboardChatHistoryRoute: typeof AuthenticatedDashboardChatHistoryRoute
  AuthenticatedDashboardContactsRoute: typeof AuthenticatedDashboardContactsRoute
  AuthenticatedDashboardIntegrationsRoute: typeof AuthenticatedDashboardIntegrationsRoute
  AuthenticatedDashboardKnowledgeRoute: typeof AuthenticatedDashboardKnowledgeRoute
  AuthenticatedDashboardLiveMonitoringRoute: typeof AuthenticatedDashboardLiveMonitoringRoute
  AuthenticatedDashboardPhoneNumbersRoute: typeof AuthenticatedDashboardPhoneNumbersRoute
  AuthenticatedDashboardSettingsRoute: typeof AuthenticatedDashboardSettingsRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
}

const AuthenticatedDashboardRouteChildren: AuthenticatedDashboardRouteChildren =
  {
    AuthenticatedDashboardAgentsRoute: AuthenticatedDashboardAgentsRoute,
    AuthenticatedDashboardAiQualityRoute: AuthenticatedDashboardAiQualityRoute,
    AuthenticatedDashboardAlertingRoute: AuthenticatedDashboardAlertingRoute,
    AuthenticatedDashboardAnalyticsRoute: AuthenticatedDashboardAnalyticsRoute,
    AuthenticatedDashboardBatchCallRoute: AuthenticatedDashboardBatchCallRoute,
    AuthenticatedDashboardBillingRoute: AuthenticatedDashboardBillingRoute,
    AuthenticatedDashboardCallHistoryRoute:
      AuthenticatedDashboardCallHistoryRoute,
    AuthenticatedDashboardChatHistoryRoute:
      AuthenticatedDashboardChatHistoryRoute,
    AuthenticatedDashboardContactsRoute: AuthenticatedDashboardContactsRoute,
    AuthenticatedDashboardIntegrationsRoute:
      AuthenticatedDashboardIntegrationsRoute,
    AuthenticatedDashboardKnowledgeRoute: AuthenticatedDashboardKnowledgeRoute,
    AuthenticatedDashboardLiveMonitoringRoute:
      AuthenticatedDashboardLiveMonitoringRoute,
    AuthenticatedDashboardPhoneNumbersRoute:
      AuthenticatedDashboardPhoneNumbersRoute,
    AuthenticatedDashboardSettingsRoute: AuthenticatedDashboardSettingsRoute,
    AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
  }

const AuthenticatedDashboardRouteWithChildren =
  AuthenticatedDashboardRoute._addFileChildren(
    AuthenticatedDashboardRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicTelephonyExotelRoute: ApiPublicTelephonyExotelRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
